package org.leafframework.data.dao.orm;
// Generated 2016-8-7 22:29:41 by Hibernate Tools 4.3.1



/**
 * TDocOtherInfo generated by hbm2java
 */
public class TDocOtherInfo  implements java.io.Serializable {


     private Integer id;
     private Integer pathItemId;
     private Boolean isArr;
     private Integer refId;
     private String name;
     private String description;
    private String json;
    public TDocOtherInfo() {
    }

    public Boolean getArr() {
        return isArr;
    }

    public void setArr(Boolean arr) {
        isArr = arr;
    }

    public String getJson() {
        return json;
    }

    public void setJson(String json) {
        this.json = json;
    }

    public TDocOtherInfo(Integer pathItemId, Boolean isArr, Integer refId, String name, String description) {
       this.pathItemId = pathItemId;
       this.isArr = isArr;
       this.refId = refId;
       this.name = name;
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getPathItemId() {
        return this.pathItemId;
    }
    
    public void setPathItemId(Integer pathItemId) {
        this.pathItemId = pathItemId;
    }
    public Boolean getIsArr() {
        return this.isArr;
    }
    
    public void setIsArr(Boolean isArr) {
        this.isArr = isArr;
    }
    public Integer getRefId() {
        return this.refId;
    }
    
    public void setRefId(Integer refId) {
        this.refId = refId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


