package org.leafframework.data.dao.orm;
// Generated 2016-7-24 17:04:36 by Hibernate Tools 4.3.1



/**
 * TDocDefinitions generated by hbm2java
 */
public class TDocDefinitions  implements java.io.Serializable {


     private Integer id;
     private Integer docId;
     private String json;
     private String createTime;
     private String updateTime;
     private String userCode;
     private String description;

    public TDocDefinitions() {
    }

    public TDocDefinitions(Integer docId, String json, String createTime, String updateTime, String userCode, String description) {
       this.docId = docId;
       this.json = json;
       this.createTime = createTime;
       this.updateTime = updateTime;
       this.userCode = userCode;
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getDocId() {
        return this.docId;
    }
    
    public void setDocId(Integer docId) {
        this.docId = docId;
    }
    public String getJson() {
        return this.json;
    }
    
    public void setJson(String json) {
        this.json = json;
    }
    public String getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }
    public String getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }
    public String getUserCode() {
        return this.userCode;
    }
    
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


