package org.leafframework.data.dao.orm;
// Generated 2016-7-27 15:04:27 by Hibernate Tools 4.3.1



/**
 * TDocTag generated by hbm2java
 */
public class TDocTag  implements java.io.Serializable {


     private Integer id;
     private int docId;
     private String name;
     private String description;
     private Integer showOrder;
     private String createTime;
     private String updateTime;

    public TDocTag() {
    }

	
    public TDocTag(int docId, String name) {
        this.docId = docId;
        this.name = name;
    }
    public TDocTag(int docId, String name, String description, Integer showOrder, String createTime, String updateTime) {
       this.docId = docId;
       this.name = name;
       this.description = description;
       this.showOrder = showOrder;
       this.createTime = createTime;
       this.updateTime = updateTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getDocId() {
        return this.docId;
    }
    
    public void setDocId(int docId) {
        this.docId = docId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getShowOrder() {
        return this.showOrder;
    }
    
    public void setShowOrder(Integer showOrder) {
        this.showOrder = showOrder;
    }
    public String getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }
    public String getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }




}


