package org.leafframework.data.dao.orm;
// Generated 2016-7-24 17:04:36 by Hibernate Tools 4.3.1



/**
 * TDocPath generated by hbm2java
 */
public class TDocPath  implements java.io.Serializable {


     private Integer id;
     private int docId;
     private String path;

    public TDocPath() {
    }

    public TDocPath(int docId, String path) {
       this.docId = docId;
       this.path = path;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getDocId() {
        return this.docId;
    }
    
    public void setDocId(int docId) {
        this.docId = docId;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }




}


