package org.leafframework.data.dao.orm;
// Generated 2016-7-24 17:04:36 by Hibernate Tools 4.3.1


import java.util.List;

/**
 * TDocRespParam generated by hbm2java
 */
public class TDocRespParam  implements java.io.Serializable {


     private Integer id;
     private int pathItemId;
     private String name;
     private String description;
     private String type;
     private String cut;
     private Integer refId;
     private Boolean isarr;
    private String userCode;

    public List getOtherInfo() {
        return otherInfo;
    }

    public void setOtherInfo(List otherInfo) {
        this.otherInfo = otherInfo;
    }

    private List otherInfo;
    public String getUserCode() {
        return userCode;
    }

    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }


    public TDocRespParam() {
    }

	
    public TDocRespParam(int pathItemId, String name) {
        this.pathItemId = pathItemId;
        this.name = name;
    }
    public TDocRespParam(int pathItemId, String name, String description, String type, String cut, Integer refId, Boolean isarr) {
       this.pathItemId = pathItemId;
       this.name = name;
       this.description = description;
       this.type = type;
       this.cut = cut;
       this.refId = refId;
       this.isarr = isarr;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getPathItemId() {
        return this.pathItemId;
    }
    
    public void setPathItemId(int pathItemId) {
        this.pathItemId = pathItemId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getCut() {
        return this.cut;
    }
    
    public void setCut(String cut) {
        this.cut = cut;
    }
    public Integer getRefId() {
        return this.refId;
    }
    
    public void setRefId(Integer refId) {
        this.refId = refId;
    }
    public Boolean getIsarr() {
        return this.isarr;
    }
    
    public void setIsarr(Boolean isarr) {
        this.isarr = isarr;
    }




}


