package org.leafframework.data.dao.orm;
// Generated 2016-7-24 17:04:36 by Hibernate Tools 4.3.1



/**
 * TDoc generated by hbm2java
 */
public class TDoc  implements java.io.Serializable {


     private Integer id;
     private String version;
     private int infoId;
     private String host;
     private String basePath;
     private String schemes;
     private Integer externalDoc;
     private Integer securityDefine;
     private String createTime;
     private String updateTime;

    public TDoc() {
    }

	
    public TDoc(int infoId, String host, String basePath, String schemes) {
        this.infoId = infoId;
        this.host = host;
        this.basePath = basePath;
        this.schemes = schemes;
    }
    public TDoc(int infoId, String host, String basePath, String schemes, Integer externalDoc, Integer securityDefine, String createTime, String updateTime) {
       this.infoId = infoId;
       this.host = host;
       this.basePath = basePath;
       this.schemes = schemes;
       this.externalDoc = externalDoc;
       this.securityDefine = securityDefine;
       this.createTime = createTime;
       this.updateTime = updateTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    public int getInfoId() {
        return this.infoId;
    }
    
    public void setInfoId(int infoId) {
        this.infoId = infoId;
    }
    public String getHost() {
        return this.host;
    }
    
    public void setHost(String host) {
        this.host = host;
    }
    public String getBasePath() {
        return this.basePath;
    }
    
    public void setBasePath(String basePath) {
        this.basePath = basePath;
    }
    public String getSchemes() {
        return this.schemes;
    }
    
    public void setSchemes(String schemes) {
        this.schemes = schemes;
    }
    public Integer getExternalDoc() {
        return this.externalDoc;
    }
    
    public void setExternalDoc(Integer externalDoc) {
        this.externalDoc = externalDoc;
    }
    public Integer getSecurityDefine() {
        return this.securityDefine;
    }
    
    public void setSecurityDefine(Integer securityDefine) {
        this.securityDefine = securityDefine;
    }
    public String getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }
    public String getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }




}


