package org.leafframework.data.dao.orm;
// Generated 2016-7-24 17:04:36 by Hibernate Tools 4.3.1



/**
 * TDocInfo generated by hbm2java
 */
public class TDocInfo  implements java.io.Serializable {


     private Integer id;
     private String version;
     private int docId;
     private String description;
     private int contactId;
     private String title;
     private String project;

    public String getProject() {
        return project;
    }

    public void setProject(String project) {
        this.project = project;
    }


    public TDocInfo() {
    }

	
    public TDocInfo(int docId, int contactId, String title) {
        this.docId = docId;
        this.contactId = contactId;
        this.title = title;
    }
    public TDocInfo(int docId, String description, int contactId, String title) {
       this.docId = docId;
       this.description = description;
       this.contactId = contactId;
       this.title = title;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    public int getDocId() {
        return this.docId;
    }
    
    public void setDocId(int docId) {
        this.docId = docId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getContactId() {
        return this.contactId;
    }
    
    public void setContactId(int contactId) {
        this.contactId = contactId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }




}


