package org.leafframework.data.dao.orm;
// Generated 2016-7-25 15:57:11 by Hibernate Tools 4.3.1



/**
 * TDocReqParam generated by hbm2java
 */
public class TDocReqParam  implements java.io.Serializable {


     private Integer id;
     private int pathItemId;
     private String name;
     private String location;
     private String description;
     private String type;
     private String defa;
     private Boolean isrequired;
     private String cut;
     private Integer refId;
     private Boolean isarr;
     private Integer valueMax;
     private Integer minValue;
     private Integer maxLength;
     private Integer minLength;
    private String userCode;
    public String getUserCode() {
        return userCode;
    }

    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }


    public TDocReqParam() {
    }

	
    public TDocReqParam(int pathItemId, String name) {
        this.pathItemId = pathItemId;
        this.name = name;
    }
    public TDocReqParam(int pathItemId, String name, String location, String description, String type, String defa, Boolean isrequired, String cut, Integer refId, Boolean isarr, Integer valueMax, Integer minValue, Integer maxLength, Integer minLength) {
       this.pathItemId = pathItemId;
       this.name = name;
       this.location = location;
       this.description = description;
       this.type = type;
       this.defa = defa;
       this.isrequired = isrequired;
       this.cut = cut;
       this.refId = refId;
       this.isarr = isarr;
       this.valueMax = valueMax;
       this.minValue = minValue;
       this.maxLength = maxLength;
       this.minLength = minLength;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getPathItemId() {
        return this.pathItemId;
    }
    
    public void setPathItemId(int pathItemId) {
        this.pathItemId = pathItemId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getDefa() {
        return this.defa;
    }
    
    public void setDefa(String defa) {
        this.defa = defa;
    }
    public Boolean getIsrequired() {
        return this.isrequired;
    }
    
    public void setIsrequired(Boolean isrequired) {
        this.isrequired = isrequired;
    }
    public String getCut() {
        return this.cut;
    }
    
    public void setCut(String cut) {
        this.cut = cut;
    }
    public Integer getRefId() {
        return this.refId;
    }
    
    public void setRefId(Integer refId) {
        this.refId = refId;
    }
    public Boolean getIsarr() {
        return this.isarr;
    }
    
    public void setIsarr(Boolean isarr) {
        this.isarr = isarr;
    }
    public Integer getValueMax() {
        return this.valueMax;
    }
    
    public void setValueMax(Integer valueMax) {
        this.valueMax = valueMax;
    }
    public Integer getMinValue() {
        return this.minValue;
    }
    
    public void setMinValue(Integer minValue) {
        this.minValue = minValue;
    }
    public Integer getMaxLength() {
        return this.maxLength;
    }
    
    public void setMaxLength(Integer maxLength) {
        this.maxLength = maxLength;
    }
    public Integer getMinLength() {
        return this.minLength;
    }
    
    public void setMinLength(Integer minLength) {
        this.minLength = minLength;
    }




}


