package org.leafframework.data.dao.orm;
// Generated 2016-7-24 17:04:36 by Hibernate Tools 4.3.1



/**
 * TDocContact generated by hbm2java
 */
public class TDocContact  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String email;
     private String url;
     private String phone;
     private String regTime;
     private String updateTime;
     private String remark;

    public TDocContact() {
    }

	
    public TDocContact(String name, String email) {
        this.name = name;
        this.email = email;
    }
    public TDocContact(String name, String email, String url, String phone, String regTime, String updateTime, String remark) {
       this.name = name;
       this.email = email;
       this.url = url;
       this.phone = phone;
       this.regTime = regTime;
       this.updateTime = updateTime;
       this.remark = remark;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getRegTime() {
        return this.regTime;
    }
    
    public void setRegTime(String regTime) {
        this.regTime = regTime;
    }
    public String getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


